---
# all commands by default will run on every push, not every commit
default_install_hook_types: [pre-push]
default_stages: [pre-push]

# some configs are only available after v2.18
minimum_pre_commit_version: '2.18'

repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.5
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: [
          'dbt-bigquery==1.5.3',
          'sqlfluff-templater-dbt==2.3.5'
        ]
      - id: sqlfluff-fix
        stages: [manual]  # this command is available only to run manually
        additional_dependencies: [
          'dbt-bigquery==1.5.3',
          'sqlfluff-templater-dbt==2.3.5'
        ]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v1.1.1
    hooks:
      - id: check-source-table-has-description
      - id: check-model-has-tests
        args: ["--test-cnt", "1", "--"]