name: "bigquery_public_dataset"
version: "1.0.0"
config-version: 2
profile: "bigquery_public_dataset"

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
packages-install-path: "dbt_packages"
clean-targets: ["target", "dbt_packages"]

require-dbt-version: [">=1.2.0"]

vars:
  util_days_start_date: "1970-01-01"
  dataset_labels:
    - key: data_owner
      value: joseph_orafu
    - key: classification
      value: public
    - key: description
      value: rittman_assessment_data

  bigquery_project_default_region: region-us

models:
  bigquery_public_dataset:  # This must match the `name:` above
    +persist_docs:
      relation: true
      columns: true

    +labels:
      data_owner: joseph_orafu
      classification: public
      description: rittman_assessment_data

    staging:
      schema: assessment_staging
      +materialized: view
      +labels:
        subject_matter: staging_objects

    intermediate:
      schema: assessment_warehouse  # typo preserved to match your actual dataset
      +materialized: view
      +labels:
        subject_matter: intermediate_tables

    warehousing:
      schema: assessment_warehouse
      +materialized: view
      +labels:
        subject_matter: analyst_facing_tables

    reporting:
      schema: assessment_analytics
      +materialized: view
      +labels:
        subject_matter: power_bi_facing_tables

    utils:
      schema: assessment_analytics
      +materialized: view
      +labels:
        subject_matter: utility_objects
