---
# The dev output is an example config for your local dbt profiles.yml
# For automation, cloud_run_job_automation is used
# In dev containers, sandbox is used
# Windows: C:\users\...\.dbt\profiles.yml
# Mac: Run "open ~/.dbt/profiles.yml"

"bigquery_public_dataset":
  target: "{{ env_var('cloud_run_job', 'sandbox') }}" # DBT_TARGET_PROFILE for a production orchestrator should be set to "cloud_run_job"
  outputs:
    cloud_run_job:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_BIGQUERY_PROJECT') }}" # DBT_BIGQUERY_PROJECT for a production orchestrator should be set to "project name"
      dataset: "" # when running in production, datasets to be prefixed with product name
      schema: "{{ env_var('DBT_BIGQUERY_SCHEMA', 'assessment_staging') }}"
      location: US
      threads: 8
    # this target should only be used when developing locally
    sandbox:
      dataset: "{{env_var('DBT_DEVELOPER_NAME', 'developer')}}"  # for sandbox this must be developer name
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: prj-rittman-assessment
      threads: 1
      type: bigquery