---
# The dev output is an example config for your local dbt profiles.yml
# For automation, cloud_run_job_automation is used
# In dev containers, sandbox is used
# Windows: C:\users\...\.dbt\profiles.yml
# Mac: Run "open ~/.dbt/profiles.yml"

bigquery_public_dataset:
  target: "{{ env_var('DBT_TARGET', 'sandbox') }}"
  outputs:
    sandbox:
      type: bigquery
      method: oauth
      project: prj-rittman-assessment
      schema: "{{ env_var('DBT_BIGQUERY_SCHEMA', 'jorafu') }}"  # leave empty to allow dbt_project.yml control
      location: US
      threads: 1
      priority: interactive
      job_execution_timeout_seconds: 300
      job_retries: 1

    cloud_run_job:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_BIGQUERY_PROJECT', 'prj-rittman-assessment') }}"
      schema: "{{ env_var('DBT_BIGQUERY_SCHEMA', 'jorafu') }}"
      location: US
      threads: 8
